DATASET:
  NAME: CLOTHING1M
  REPRESENTATION_MODEL: "dinov2_small"
  REPRESENTATION_DIM: 384
  ROOT_DIR: '/cs/labs/daphna/data/clothing1m'
  VAL_RATIO: 0.0
  AUG_METHOD: 'clothing1m'
MODEL:
  TYPE: resnet50
  NUM_CLASSES: 14
OPTIM:
  TYPE: 'sgd'
  BASE_LR: 0.002  #
  LR_POLICY: steps #
  STEPS: [0, 40, 80] #
  LR_MULT: 0.1 #
  MOMENTUM: 0.9  #
  NESTEROV: True
  WEIGHT_DECAY: 0.001  #
TRAIN:
  SPLIT: train
  BATCH_SIZE: 32
  IM_SIZE: 224
  BALANCE_CLASSES: True
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 224
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: True
NOISE:
  NOISE_TYPE: 'noisy_label'
  NOISE_RATE: 0.38
