DATASET:
  NAME: CLOTHING1M
  REPRESENTATION_MODEL: "dinov2_small"
  REPRESENTATION_DIM: 384
  ROOT_DIR: '.data/clothing1m'
  VAL_RATIO: 0.0
  AUG_METHOD: 'clothing1m'
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 14
OPTIM:
  TYPE: 'sgd'
  BASE_LR: 0.025
  LR_POLICY: cos
  LR_MULT: 0.1
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0003
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 64
  IM_SIZE: 224
  EVAL_PERIOD: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 224
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: True
ACTIVE_LEARNING:
  MAX_ITER: 5
  DELTA_RESOLUTION: 0.05
  MAX_DELTA: 1.1
NOISE:
  NOISE_TYPE: 'noisy_label'
  NOISE_RATE: 0.38