DATASET:
  NAME: IMAGENET50
  REPRESENTATION_MODEL: "dinov2"
  REPRESENTATION_DIM: 384
  ROOT_DIR: '.data/imagenet_new/'
  VAL_RATIO: 0.0
  AUG_METHOD: 'hflip'
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 50
OPTIM:
  TYPE: 'sgd'
  BASE_LR: 0.01
  LR_POLICY: cos
  LR_MULT: 0.1
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0003
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 50
  IM_SIZE: 224
  EVAL_PERIOD: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 224
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: True
ACTIVE_LEARNING:
  MAX_ITER: 5
  DELTA_RESOLUTION: 0.05
  MAX_DELTA: 1.1
NOISE:
  NOISE_TYPE: 'sym'